version: '2'
services:

  npm-install:
    image: netrunner-node
    volumes:
      - .:/netrunner
    command: |
      sh -c "npm install
             ./node_modules/.bin/bower --allow-root install"

  stylus-css:
    image: netrunner-node
    volumes:
      - .:/netrunner
    command: ./node_modules/.bin/stylus -w src/css -o resources/public/css/

  lein-cljs:
    image: clojure:latest
    volumes:
      - .:/netrunner
    ports:
      - 3449:3449
    command: |
      sh -c "cd /netrunner
             lein deps
             lein cljsbuild auto dev"

  lein-netrunner:
    image: clojure:latest
    volumes:
      - .:/netrunner
    ports:
      - 1042:1042
    environment:
      MONGODB_HOST: mongodb
      ZMQ_HOST: "*"
    links:
      - mongodb
    depends_on:
      - mongodb
    command: |
      sh -c "cd /netrunner
             lein fetch
             lein run dev"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /tmp/netrunner/mongo-data:/data/db