version: '2'
services:

  npm-install:
    image: meccg-node
    volumes:
      - .:/meccg
    command: |
      sh -c "npm install
             ./node_modules/.bin/bower --allow-root install"

  fetch-cards:
    image: meccg-node
    volumes:
      - .:/meccg
    links:
      - mongo
    environment: 
      OPENSHIFT_MONGODB_DB_HOST: mongo 
    command: npm run fetch

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /tmp/meccg/mongo-data:/data/db

  lein-cljs:
    image: clojure:latest
    volumes:
      - .:/meccg
    command: |
      sh -c "cd /meccg
             lein cljsbuild auto dev"

  lein-meccg:
    image: clojure:latest
    volumes:
      - .:/meccg
    ports:
      - 7001:7001
    environment:
      ZMQ_HOST: "*"
    command: |
      sh -c "cd /meccg
             lein run"

  stylus-css:
    image: meccg-node
    volumes:
      - .:/meccg
    command: ./node_modules/.bin/stylus -w src/css -o resources/public/css/

  coffee-server:
    image: meccg-node
    volumes:
      - .:/meccg
    ports:
      - 1042:1042
    links:
      - mongo
      - lein-meccg
    environment:
      MONGO_URL: mongodb://mongo:27017/meccg
      CLOJURE_HOST: lein-meccg
    command: ./node_modules/.bin/coffee server.coffee
